export let productList = [
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
  {
    id: 1.01,
    desEng: `Delicious handmade pizza`,
    desBangla: "হাতের তৈরি সুস্বাদু পিজ্জা।",
    price: 500,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`white`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Freshly prepared pizza with high-quality ingredients for a delightful experience.`,
  },
  {
    id: 1.02,
    desEng: `Spicy chicken burger`,
    desBangla: "মসলাদার চিকেন বার্গার।",
    price: 350,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A zesty chicken burger packed with flavor and premium spices.`,
  },
  {
    id: 1.03,
    desEng: `Chilled chocolate milkshake`,
    desBangla: "ঠান্ডা চকোলেট মিল্কশেক।",
    price: 220,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`brown`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Rich, creamy chocolate milkshake for a refreshing treat.`,
  },
  {
    id: 1.04,
    desEng: `Crispy french fries`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 180,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Perfectly fried crispy french fries with a touch of salt.`,
  },
  {
    id: 1.05,
    desEng: `Refreshing lemonade`,
    desBangla: "সজীবতা দানকারী লেবুর শরবত।",
    price: 150,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `beverage`,
    color: [[`transparent`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A cool glass of lemonade to quench your thirst.`,
  },
  {
    id: 1.06,
    desEng: `Classic beef burger`,
    desBangla: "ক্লাসিক বিফ বার্গার।",
    price: 400,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Juicy beef patty with fresh veggies and soft buns.`,
  },
  {
    id: 1.07,
    desEng: `Tandoori chicken pizza`,
    desBangla: "তন্দুরি চিকেন পিজ্জা।",
    price: 580,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `food`,
    color: [[`orange`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `A fusion pizza topped with spicy tandoori chicken.`,
  },
  {
    id: 1.08,
    desEng: `Strawberry ice cream`,
    desBangla: "স্ট্রবেরি আইসক্রিম।",
    price: 120,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `dessert`,
    color: [[`pink`, `https://i.postimg.cc/50Sds2r4/1001.webp`]],
    longDes: `Creamy strawberry-flavored ice cream for a sweet ending.`,
  },
];
